<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\Images\radio-button\**" />
    <EmbeddedResource Remove="Resources\Images\radio-button\**" />
    <None Remove="Resources\Images\radio-button\**" />
    <Page Remove="Resources\Images\radio-button\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Images\adjustment.png" />
    <None Remove="Resources\Images\background2.jpg" />
    <None Remove="Resources\Images\battleship.png" />
    <None Remove="Resources\Images\Components\accept.png" />
    <None Remove="Resources\Images\Components\delete-hover.png" />
    <None Remove="Resources\Images\Components\delete.png" />
    <None Remove="Resources\Images\cross.png" />
    <None Remove="Resources\Images\cruiser.png" />
    <None Remove="Resources\Images\destroyer.png" />
    <None Remove="Resources\Images\exitButton.png" />
    <None Remove="Resources\Images\hoveredNoneSelectedButton.png" />
    <None Remove="Resources\Images\hoveredSelectedButton.png" />
    <None Remove="Resources\Images\load-file.png" />
    <None Remove="Resources\Images\multiplayer.png" />
    <None Remove="Resources\Images\noneSelectedButton.png" />
    <None Remove="Resources\Images\online.png" />
    <None Remove="Resources\Images\Radiobutton\radio-hover-focus.png" />
    <None Remove="Resources\Images\Radiobutton\radio-hover.png" />
    <None Remove="Resources\Images\Radiobutton\radio.png" />
    <None Remove="Resources\Images\Radiobutton\selected-radio-hover-focus.png" />
    <None Remove="Resources\Images\Radiobutton\selected-radio-hover.png" />
    <None Remove="Resources\Images\Radiobutton\selected-radio.png" />
    <None Remove="Resources\Images\restricted.png" />
    <None Remove="Resources\Images\restriction.png" />
    <None Remove="Resources\Images\selectedButton.png" />
    <None Remove="Resources\Images\settings.png" />
    <None Remove="Resources\Images\settings2.png" />
    <None Remove="Resources\Images\singelplayer.png" />
    <None Remove="Resources\Images\submarine.png" />
    <None Remove="Resources\Images\water-field.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\adjustment.png" />
    <Resource Include="Resources\Images\background2.jpg" />
    <Resource Include="Resources\Images\battleship.png" />
    <Resource Include="Resources\Images\Components\accept.png" />
    <Resource Include="Resources\Images\Components\delete-hover.png" />
    <Resource Include="Resources\Images\Components\delete.png" />
    <Resource Include="Resources\Images\cross.png" />
    <Resource Include="Resources\Images\cruiser.png" />
    <Resource Include="Resources\Images\destroyer.png" />
    <Resource Include="Resources\Images\load-file.png" />
    <Resource Include="Resources\Images\multiplayer.png" />
    <Resource Include="Resources\Images\online.png" />
    <Resource Include="Resources\Images\Radiobutton\radio-hover-focus.png" />
    <Resource Include="Resources\Images\Radiobutton\radio-hover.png" />
    <Resource Include="Resources\Images\Radiobutton\radio.png" />
    <Resource Include="Resources\Images\Radiobutton\selected-radio-hover-focus.png" />
    <Resource Include="Resources\Images\Radiobutton\selected-radio-hover.png" />
    <Resource Include="Resources\Images\Radiobutton\selected-radio.png" />
    <Resource Include="Resources\Images\restricted.png" />
    <Resource Include="Resources\Images\restriction.png" />
    <Resource Include="Resources\Images\settings.png" />
    <Resource Include="Resources\Images\singelplayer.png" />
    <Resource Include="Resources\Images\submarine.png" />
    <Resource Include="Resources\Images\water-field.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Playground\" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Resources\Components\MenuButton.xaml">
      <CustomToolNamespace>Components</CustomToolNamespace>
    </Page>
  </ItemGroup>

</Project>
